---
  - hosts: localhost
    become: yes
    vars_files:
      - vars/all.yaml
    tasks:
      - name: Install packages
        import_tasks: tasks/install_packages.yaml
      - name: Copy configurations
        import_tasks: tasks/copy_configuration.yaml
