- name: copy i3 config file
  copy:
    src: files/i3-config.conf
    dest: /home/ersandro/.config/i3/config
    owner: ersandro
    group: ersandro
    mode: u=rw,g=r,o=r

- name: copy Alacritty config file
  copy:
    src: files/alacritty.yml
    dest: /home/ersandro/.config/alacritty.yml
    owner: ersandro
    group: ersandro
    mode: u=rw,g=r,o=r
