- name: copy i3 config file
  copy:
    src: files/i3-config.conf
    dest: /home/ersandro/.config/i3/config
    owner: ersandro
    group: ersandro
    mode: u=rw,g=r,o=r

- name: copy Alacritty config file
  copy:
    src: files/alacritty.yml
    dest: /home/ersandro/.config/alacritty.yml
    owner: ersandro
    group: ersandro
    mode: u=rw,g=r,o=r

- name: copy nitrogen last wallpaper config
  copy:
    src: files/bg-saved.cfg
    dest: /home/ersandro/.config/nitrogen/bg-saved.cfg
    owner: ersandro
    group: ersandro
    mode: u=rw,g=r,o=r

- name: copy wallpaper
  copy:
    src: files/wallpaper.jpeg
    dest: /home/ersandro/Pictures/wallpaper.jpeg
    owner: ersandro
    group: ersandro
    mode: u=rw,g=r,o=r
